---
language: generic
jobs:
  include:
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -u "$UID" -v "$PWD:$PWD" -w "$PWD" lpenz/omnilint
    - name: linkchecker
      addons: { apt: { packages: [ linkchecker ] } }
      script: linkchecker index.html

